#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path


def is_arco_payload(path: Path) -> bool:
    """Return True only when the RAW JSON explicitly carries ARCO provenance."""
    try:
        obj = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        # A malformed/non-JSON RAW should not silently survive a scientific migration.
        return False

    def walk(x):
        if isinstance(x, dict):
            prov = x.get("_predicta_provenance")
            if isinstance(prov, dict) and str(prov.get("historical_backend", "")).upper() == "ARCO":
                return True
            if str(x.get("historical_backend", "")).upper() == "ARCO":
                return True
            return any(walk(v) for v in x.values())
        if isinstance(x, list):
            return any(walk(v) for v in x)
        return False

    return walk(obj)


def iter_raw_json(root: Path):
    if not root.exists():
        return []
    return sorted(p for p in root.rglob("*.json") if p.is_file())


def move_preserving_tree(path: Path, source_root: Path, dest_root: Path) -> Path:
    rel = path.relative_to(source_root)
    dest = dest_root / rel
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists():
        stem = dest.stem
        suffix = dest.suffix
        i = 1
        while dest.exists():
            dest = dest.with_name(f"{stem}__{i}{suffix}")
            i += 1
    shutil.move(str(path), str(dest))
    return dest


def main():
    ap = argparse.ArgumentParser(
        description="Quarantine legacy Open-Meteo historical RAW so Predicta can rebuild it through ARCO."
    )
    ap.add_argument("--region", default="n", choices=["n", "ne", "seco", "s"])
    ap.add_argument("--store-root", default="data/climate_store")
    ap.add_argument("--archive-root", default="data/raw/climate/annual_archive")
    ap.add_argument("--quarantine-root", default="data/climate_store_quarantine")
    ap.add_argument("--reports-root", default="outputs/reports/climate")
    ap.add_argument("--apply", action="store_true", help="Actually move files. Without this flag, only report.")
    args = ap.parse_args()

    region = args.region
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    quarantine_base = Path(args.quarantine_root) / region / f"legacy_openmeteo_{stamp}"

    roots = [
        ("store_hourly", Path(args.store_root) / region / "hourly"),
        ("store_daily", Path(args.store_root) / region / "daily"),
        ("archive_hourly", Path(args.archive_root) / region / "hourly"),
        ("archive_daily", Path(args.archive_root) / region / "daily"),
    ]

    summary = {
        "region": region,
        "apply": args.apply,
        "quarantine": str(quarantine_base),
        "roots": {},
        "total_json": 0,
        "arco_kept": 0,
        "legacy_found": 0,
        "legacy_moved": 0,
        "report_files_moved": 0,
    }

    for label, root in roots:
        files = iter_raw_json(root)
        info = {"root": str(root), "exists": root.exists(), "json": len(files), "arco": 0, "legacy": 0, "moved": 0}
        for p in files:
            summary["total_json"] += 1
            if is_arco_payload(p):
                info["arco"] += 1
                summary["arco_kept"] += 1
                continue
            info["legacy"] += 1
            summary["legacy_found"] += 1
            if args.apply:
                dest = move_preserving_tree(p, root, quarantine_base / label)
                info["moved"] += 1
                summary["legacy_moved"] += 1
        summary["roots"][label] = info

    # Invalidate only generated manifests/checkpoints for this region.
    # They are regenerated by script 53 and may otherwise reference quarantined RAW.
    reports_root = Path(args.reports_root)
    report_patterns = [
        f"{region}_e2_download_*.json",
        f"{region}_e3_download_*.json",
        f"{region}_annual_download_checkpoint.json",
        f"{region}_multiyear_download_*.json",
        f"{region}_e2_prepare_*.json",
        f"{region}_e3_prepare_*.json",
    ]
    report_candidates = []
    if reports_root.exists():
        seen = set()
        for pat in report_patterns:
            for p in reports_root.glob(pat):
                if p.is_file() and p not in seen:
                    seen.add(p)
                    report_candidates.append(p)

    summary["generated_reports_found"] = len(report_candidates)
    if args.apply:
        for p in report_candidates:
            dest = quarantine_base / "generated_reports" / p.name
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(p), str(dest))
            summary["report_files_moved"] += 1

    print(json.dumps(summary, ensure_ascii=False, indent=2))
    if args.apply:
        print("LEGACY_CLIMATE_CACHE_QUARANTINE_OK")
        print("Next: rerun scripts/47_run_full_automation.py. Missing historical RAW will be rebuilt through ARCO.")
    else:
        print("DRY_RUN_ONLY: add --apply to move legacy RAW files.")


if __name__ == "__main__":
    main()
